### ISSUE TITLE
Substitutions 2

### ISSUE THREAD

**Issue by djbe** [bahlo/xkcd-substitutions#2]
As you've probably already noticed:
http://xkcd.com/1625/

Some other additions:
https://xkcd.com/1004/
https://xkcd.com/1031/

**Comment by bahlo** [comment]
Already working on 1625, but thanks for the notice and the batman link! :grin::+1:

**Comment by bahlo** [comment]
See [v1.2](https://github.com/bahlo/xkcd-substitutions/releases/tag/v1.2) :ok_hand:

**Comment by bahlo** [comment]
And [v1.3](https://github.com/bahlo/xkcd-substitutions/releases/tag/v1.3), closing now! :blush:
